Repository getsentry/sentry-javascript, pull requests merged in 2021-12, with the labels that each got.

#4100 test: Add browser based scenarios
  .eslintrc.js
  .gitignore
  packages/eslint-config-sdk/src/index.js
  scenarios/browser/basic-capture-exception/index.js
  scenarios/browser/basic-capture-exception/package.json
  scenarios/browser/basic-capture-message/index.js
  scenarios/browser/basic-capture-message/package.json
  scenarios/browser/basic-custom-integration/index.js
  scenarios/browser/basic-custom-integration/package.json
  scenarios/browser/basic-custom-transport/index.js
  scenarios/browser/basic-custom-transport/package.json
  scenarios/browser/basic-no-client-reports/index.js
  scenarios/browser/basic-no-client-reports/package.json
  scenarios/browser/basic-no-default-integrations/index.js
  scenarios/browser/basic-no-default-integrations/package.json
  scenarios/browser/basic-no-dsn/index.js
  scenarios/browser/basic-no-dsn/package.json
  scenarios/browser/basic-no-sessions/index.js
  scenarios/browser/basic-no-sessions/package.json
  scenarios/browser/basic-with-debug/index.js
  scenarios/browser/basic-with-debug/package.json
  scenarios/browser/basic-with-sessions/index.js
  scenarios/browser/basic-with-sessions/package.json
  scenarios/browser/basic-with-tunnel/index.js
  scenarios/browser/basic-with-tunnel/package.json
  scenarios/browser/basic/index.js
  scenarios/browser/basic/package.json
  scenarios/browser/nextjs-client/index.js
  scenarios/browser/nextjs-client/package.json
  scenarios/browser/package.json
  scenarios/browser/perf-auto/index.js
  scenarios/browser/perf-auto/package.json
  scenarios/browser/perf-manual/index.js
  scenarios/browser/perf-manual/package.json
  scenarios/browser/react/index.js
  scenarios/browser/react/package.json
  scenarios/browser/webpack.js
  scenarios/browser/yarn.lock
Labels: Status: In Progress

#4216 fix(nextjs): Add sideEffects flag to NextJS SDK
  packages/nextjs/package.json
Labels: Package: nextjs

#4093 feat(nextjs): Support Next.js v12
  packages/nextjs/package.json
Labels: Status: Stale
