Repository getsentry/sentry-javascript, pull requests merged in 2023-02, with the labels that each got.

#7010 fix(replay): Catch style mutation handling & null events in rrweb
  packages/replay/package.json
  yarn.lock
Labels: Package: replay

#6988 fix(replay): Handle compression failures more robustly
  packages/replay/.eslintrc.js
  packages/replay/src/eventBuffer/EventBufferArray.ts
  packages/replay/src/eventBuffer/EventBufferCompressionWorker.ts
  packages/replay/src/eventBuffer/EventBufferProxy.ts
  packages/replay/src/eventBuffer/WorkerHandler.ts
  packages/replay/src/replay.ts
  packages/replay/src/types.ts
  packages/replay/src/util/addEvent.ts
  packages/replay/src/worker/worker.js
  packages/replay/test/integration/rateLimiting.test.ts
  packages/replay/test/integration/sendReplayEvent.test.ts
  packages/replay/test/integration/stop.test.ts
  packages/replay/test/unit/eventBuffer.test.ts
  packages/replay/test/unit/eventBuffer/EventBufferArray.test.ts
  packages/replay/test/unit/eventBuffer/EventBufferCompressionWorker.test.ts
  packages/replay/test/unit/eventBuffer/EventBufferProxy.test.ts
  packages/replay/test/unit/util/addEvent.test.ts
  packages/replay/test/unit/worker/Compressor.test.ts
  packages/replay/test/utils/setupReplayContainer.ts
  packages/replay/worker/src/Compressor.ts
  packages/replay/worker/src/handleMessage.ts
Labels: Package: replay

#7016 build: Add `yarn changelog` command
  docs/publishing-a-release.md
  package.json
  scripts/get-commit-list.ts
Labels: Dev: Build

#7019 ci: Improve gitflow process
  .github/workflows/gitflow-sync-develop.yml
  .github/workflows/gitflow-sync-master.yml
Labels: Dev: CI

#7027 [Gitflow] Merge master into develop
  lerna.json
  packages/angular/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-tests/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#7026 ci(gitflow): Use personal access token to create PR
  .github/workflows/gitflow-sync-develop.yml
  .github/workflows/gitflow-sync-master.yml
Labels: Dev: CI

#7021 ci: Skip CI when syncing develop<>master
  .github/workflows/build.yml
Labels: Dev: CI

#7033 fix(replay): Don't mangle private `_cssText` rrweb property
  rollup/plugins/bundlePlugins.js
Labels: Package: replay

#7034 ci: Fix invalid yaml
  .github/workflows/build.yml
  .github/workflows/gitflow-sync-master.yml
Labels: Dev: CI

#7087 feat(replay): Improve rrweb error ignoring
  packages/replay/src/coreHandlers/handleGlobalEvent.ts
  packages/replay/src/util/isRrwebError.ts
  packages/replay/test/integration/coreHandlers/handleGlobalEvent.test.ts
Labels: Package: replay

#7038 ci: Fix yaml
  .github/workflows/gitflow-sync-master.yml
Labels: Dev: CI

#7098 fix(replay): Update `worker.js` to remove console log
  packages/replay/src/worker/worker.js
Labels: ci-skip-cache

#7101 chore(replay): Link to Docs for CDN bundle installation
  packages/replay/README.md
Labels: ci-skip-cache

#7107 ci: fix yaml (again)
  .github/workflows/build.yml
  .github/workflows/clear-cache.yml
  .github/workflows/gitflow-sync-master.yml
  package.json
  packages/ember/package.json
Labels: Dev: CI

#7093 feat(replay): Send client_report when replay sending fails
  packages/replay/src/replay.ts
  packages/replay/src/util/addEvent.ts
  packages/types/src/clientreport.ts
Labels: Package: replay

#7109 build: Update `apollo-server` to get rid of yarn resolution
  package.json
  packages/node-integration-tests/package.json
  yarn.lock
Labels: Dev: Build

#7124 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-tests/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#7116 fix(tracing): Export `defaultStackParser` from tracing CDN bundles
  packages/tracing/src/index.bundle.ts
Labels: ci-skip-cache

#7146 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-tests/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#7163 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-tests/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#7164 [Gitflow] Merge master into develop
  packages/replay/README.md
Labels: Dev: Gitflow

#7141 build: Improve CI cache
  .github/workflows/auto-release.yml
  .github/workflows/build.yml
  .gitignore
  .prettierignore
  nx.json
  package.json
Labels: Dev: CI, Dev: Build

#7139 ref(replay): Extract worker into dedicated package
  package.json
  packages/replay-worker/.eslintignore
  packages/replay-worker/.eslintrc.js
  packages/replay-worker/.gitignore
  packages/replay-worker/LICENSE
  packages/replay-worker/README.md
  packages/replay-worker/jest.config.js
  packages/replay-worker/package.json
  packages/replay-worker/rollup.worker.config.js
  packages/replay-worker/src/Compressor.ts
  packages/replay-worker/src/handleMessage.ts
  packages/replay-worker/src/worker.ts
  packages/replay-worker/test/tsconfig.json
  packages/replay-worker/test/unit/Compressor.test.ts
  packages/replay-worker/tsconfig.json
  packages/replay-worker/tsconfig.test.json
  packages/replay-worker/vendor/index.d.ts
  packages/replay-worker/vendor/index.js
  packages/replay-worker/vendor/worker.d.ts
  packages/replay/.eslintrc.js
  packages/replay/package.json
  packages/replay/rollup.npm.config.js
  packages/replay/src/eventBuffer/index.ts
  packages/replay/src/worker/worker.js
  packages/replay/tsconfig.worker.json
  yarn.lock
Labels: Package: replay

#7172 fix(integration): Ensure dedupe integration ignores non-errors
  packages/browser/src/integrations/dedupe.ts
  packages/browser/test/integration/suites/api.js
  packages/integrations/src/dedupe.ts
  packages/integrations/test/dedupe.test.ts
Labels: Type: Bug, Package: Browser, Feature: Integrations

#7173 build(replay): Improve replay-worker build
  packages/replay-worker/package.json
  packages/replay-worker/rollup.worker.config.js
  packages/replay-worker/src/_worker.ts
  packages/replay-worker/src/index.ts
  packages/replay-worker/src/worker.ts
  packages/replay-worker/tsconfig.types.json
  packages/replay-worker/vendor/index.d.ts
  packages/replay-worker/vendor/worker.d.ts
  yarn.lock
Labels: Package: replay

#7174 ref(replay): Improve logging for stopped replay
  packages/replay/src/replay.ts
  packages/replay/src/types.ts
  packages/replay/src/util/addEvent.ts
Labels: Package: replay

#7203 build: Add size limit info to releases
  .github/workflows/build.yml
  .github/workflows/release-size-info.yml
Labels: Dev: CI, Dev: Build

#7213 ci: Fix auto-release workflow
  .github/workflows/auto-release.yml
Labels: Dev: CI

#7214 ci: Ensure we can actually run size-limit for release branches
  .github/workflows/build.yml
Labels: Dev: CI

#7218 [Gitflow] Merge develop into master
  .github/workflows/auto-release.yml
  .github/workflows/build.yml
  packages/integration-tests/README.md
  packages/integration-tests/suites/replay/multiple-pages/init.js
  packages/integration-tests/suites/replay/multiple-pages/page-0.html
  packages/integration-tests/suites/replay/multiple-pages/subject.js
  packages/integration-tests/suites/replay/multiple-pages/template.html
  packages/integration-tests/suites/replay/multiple-pages/test.ts
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-0-snap-full
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-0-snap-full-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-1-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-1-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-2-snap-full
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-2-snap-full-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-3-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-3-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-4-snap-full
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-4-snap-full-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-5-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-5-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-6-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-6-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-7-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-7-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-8-snap-full
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-8-snap-full-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-9-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-9-snap-incremental-chromium
  packages/integration-tests/suites/replay/privacy/test.ts-snapshots/privacy.json
  packages/integration-tests/utils/fixtures.ts
  packages/integration-tests/utils/generatePage.ts
  packages/integration-tests/utils/replayEventTemplates.ts
  packages/integration-tests/utils/replayHelpers.ts
Labels: Dev: Gitflow

#7220 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-tests/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#7219 test(replay): Normalize time offset in DOM snapshots
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-1-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-1-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-3-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-3-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-5-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-5-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-6-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-6-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-7-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-7-snap-incremental-chromium
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-9-snap-incremental
  packages/integration-tests/suites/replay/multiple-pages/test.ts-snapshots/seg-9-snap-incremental-chromium
  packages/integration-tests/utils/replayHelpers.ts
Labels: Type: Tests, Package: replay

#7221 ci: Fix adding size info to release
  .github/workflows/release-size-info.yml
Labels: Dev: CI

#7235 ci: Run nightly build without cache
  .github/workflows/build.yml
Labels: Dev: CI

#7240 test(replay): Add test for continuous flushing
  packages/integration-tests/package.json
  packages/integration-tests/suites/replay/flushing/init.js
  packages/integration-tests/suites/replay/flushing/subject.js
  packages/integration-tests/suites/replay/flushing/template.html
  packages/integration-tests/suites/replay/flushing/test.ts
  packages/integration-tests/suites/replay/privacyBlock/test.ts-snapshots/privacy.json
  packages/integration-tests/suites/replay/privacyDefault/test.ts-snapshots/privacy.json
Labels: Type: Tests, Package: replay

#7243 ci: Add timeout to integration tests job
  .github/workflows/build.yml
Labels: Dev: CI

#7252 test(replay): Ensure that unicode characters are handled correctly
  packages/integration-tests/suites/replay/unicode/compressed/init.js
  packages/integration-tests/suites/replay/unicode/compressed/test.ts
  packages/integration-tests/suites/replay/unicode/compressed/test.ts-snapshots/unicode-compressed-chromium.json
  packages/integration-tests/suites/replay/unicode/compressed/test.ts-snapshots/unicode-compressed-firefox.json
  packages/integration-tests/suites/replay/unicode/compressed/test.ts-snapshots/unicode-compressed-webkit.json
  packages/integration-tests/suites/replay/unicode/compressed/test.ts-snapshots/unicode-compressed.json
  packages/integration-tests/suites/replay/unicode/subject.js
  packages/integration-tests/suites/replay/unicode/template.html
  packages/integration-tests/suites/replay/unicode/uncompressed/init.js
  packages/integration-tests/suites/replay/unicode/uncompressed/test.ts
  packages/integration-tests/suites/replay/unicode/uncompressed/test.ts-snapshots/unicode-uncompressed-chromium.json
  packages/integration-tests/suites/replay/unicode/uncompressed/test.ts-snapshots/unicode-uncompressed-firefox.json
  packages/integration-tests/suites/replay/unicode/uncompressed/test.ts-snapshots/unicode-uncompressed-webkit.json
  packages/integration-tests/suites/replay/unicode/uncompressed/test.ts-snapshots/unicode-uncompressed.json
Labels: Type: Tests, Package: replay

#7251 test(replay): Add Playwright tests for error-mode and error linking
  packages/integration-tests/suites/replay/errors/droppedError/init.js
  packages/integration-tests/suites/replay/errors/droppedError/test.ts
  packages/integration-tests/suites/replay/errors/errorMode/test.ts
  packages/integration-tests/suites/replay/errors/errorsInSession/init.js
  packages/integration-tests/suites/replay/errors/errorsInSession/test.ts
  packages/integration-tests/suites/replay/errors/init.js
  packages/integration-tests/suites/replay/errors/subject.js
  packages/integration-tests/suites/replay/errors/template.html
  packages/integration-tests/utils/replayEventTemplates.ts
Labels: Type: Tests, Package: replay

#7285 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-tests/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#7282 fix(ember): Disable performance in FastBoot
  packages/ember/addon/instance-initializers/sentry-performance.ts
Labels: Package: ember

#7301 fix(serverless): Capture custom tags in GCP Background and CloudEvent function error events
  packages/serverless/src/gcpfunction/cloud_events.ts
  packages/serverless/src/gcpfunction/events.ts
Labels: Package: serverless
