Repository getsentry/sentry-javascript, pull requests merged in 2023-12, with the labels that each got.

#9774 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/astro/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/bun/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/deno/package.json
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/feedback/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-experimental/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vercel-edge/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#9819 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/astro/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/bun/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/deno/package.json
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/feedback/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-experimental/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vercel-edge/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#9853 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/astro/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/bun/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/deno/package.json
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/feedback/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-experimental/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vercel-edge/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#9919 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/astro/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/bun/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/deno/package.json
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/feedback/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-experimental/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vercel-edge/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#9946 feat(breadcrumbs): Send component names on UI breadcrumbs
  packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/template.html
  packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/click/test.ts
  packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/textInput/template.html
  packages/browser-integration-tests/suites/integrations/Breadcrumbs/dom/textInput/test.ts
  packages/browser/src/integrations/breadcrumbs.ts
Labels: ci-skip-cache

#9895 chore(biome): enable noUnusedImports rule
  biome.json
  package.json
  packages/angular/test/tracing.test.ts
  packages/astro/test/server/middleware.test.ts
  packages/browser-integration-tests/suites/public-api/startTransaction/init.js
  packages/browser/src/integrations/breadcrumbs.ts
  packages/browser/src/integrations/trycatch.ts
  packages/core/src/integration.ts
  packages/core/src/integrations/metadata.ts
  packages/core/src/metrics/utils.ts
  packages/e2e-tests/test-applications/create-remix-app-v2/app/entry.server.tsx
  packages/e2e-tests/test-applications/create-remix-app/app/entry.server.tsx
  packages/e2e-tests/test-applications/generic-ts3.8/index.ts
  packages/e2e-tests/test-applications/nextjs-app-dir/tests/async-context-edge.test.ts
  packages/e2e-tests/test-applications/node-hapi-app/tests/server.test.ts
  packages/e2e-tests/test-applications/react-create-hash-router/src/pages/Index.tsx
  packages/e2e-tests/test-applications/react-create-hash-router/src/pages/User.tsx
  packages/e2e-tests/test-applications/react-router-6-use-routes/src/pages/Index.tsx
  packages/e2e-tests/test-applications/react-router-6-use-routes/src/pages/User.tsx
  packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/src/pages/Index.tsx
  packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/src/pages/User.tsx
  packages/e2e-tests/test-applications/standard-frontend-react/src/pages/Index.tsx
  packages/e2e-tests/test-applications/standard-frontend-react/src/pages/User.tsx
  packages/gatsby/test/integration.test.tsx
  packages/nextjs/src/common/_error.ts
  packages/nextjs/src/config/templates/routeHandlerWrapperTemplate.ts
  packages/nextjs/src/config/templates/serverComponentWrapperTemplate.ts
  packages/nextjs/src/edge/wrapApiHandlerWithSentry.ts
  packages/nextjs/test/integration/components/Layout.tsx
  packages/nextjs/test/integration/components/List.tsx
  packages/nextjs/test/integration/components/ListDetail.tsx
  packages/nextjs/test/integration/components/ListItem.tsx
  packages/node-experimental/src/integrations/http.ts
  packages/node-experimental/src/otel/contextManager.ts
  packages/node-experimental/src/sdk/api.ts
  packages/node-experimental/src/sdk/scope.ts
  packages/node-experimental/test/integration/transactions.test.ts
  packages/node-experimental/test/sdk/scope.test.ts
  packages/node/test/integrations/localvariables.test.ts
  packages/opentelemetry/src/spanExporter.ts
  packages/react/test/profiler.test.tsx
  packages/react/test/reactrouterv4.test.tsx
  packages/react/test/reactrouterv5.test.tsx
  packages/react/test/redux.test.ts
  packages/remix/test/integration/app_v2/entry.server.tsx
  packages/remix/test/integration/common/routes/server-side-unexpected-errors.$id.tsx
  packages/replay/test/integration/rrweb.test.ts
  packages/sveltekit/src/client/handleError.ts
  packages/sveltekit/test/common/utils.test.ts
  packages/vue/src/tracing.ts
Labels: ci-codecov-ai-review

#9971 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/astro/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/bun/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/deno/package.json
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/feedback/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-experimental/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/opentelemetry/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/rollup-utils/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vercel-edge/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow
