Repository getsentry/sentry-javascript, pull requests merged in 2023-07, with the labels that each got.

#8048 fix(node): report errorMiddleware errors as unhandled
  packages/node-integration-tests/suites/express/handle-error/test.ts
  packages/node/src/handlers.ts
Labels: Status: In Progress

#8437 build: Update lerna to 7.1.1
  lerna.json
  nx.json
  package.json
  yarn.lock
Labels: Dev: Build

#8466 build(angular): Avoid loading all `@types/` packages
  packages/angular/tsconfig.json
Labels: Package: Angular

#8330 feat(types): Allow `user.id` to be a number
  packages/types/src/session.ts
  packages/types/src/user.ts
Labels: Status: Stale

#8513 [Gitflow] Merge master into develop
  CHANGELOG.md
Labels: Dev: Gitflow

#8518 [Gitflow] Merge master into develop
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#8525 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#8547 fix(replay): Better session storage check
  packages/replay/src/util/hasSessionStorage.ts
Labels: Type: Bug, Package: replay

#8553 build: Ensure `build:dev:watch` commands work
  packages/browser/package.json
  packages/integration-shims/package.json
  packages/replay-worker/package.json
Labels: Dev: Build

#8572 [Gitflow] Merge master into develop
  CHANGELOG.md
Labels: Dev: Gitflow

#8591 fix(replay): Ensure multi click has correct timestamps
  packages/browser-integration-tests/suites/replay/slowClick/multiClick/test.ts
  packages/replay/src/coreHandlers/handleClick.ts
  packages/replay/src/eventBuffer/EventBufferArray.ts
  packages/replay/src/eventBuffer/EventBufferCompressionWorker.ts
  packages/replay/src/util/addEvent.ts
  packages/replay/src/util/timestamp.ts
Labels: Type: Bug, Package: replay

#8585 test(e2e): Use `latest || *` instead of `*` as version
  packages/e2e-tests/README.md
  packages/e2e-tests/test-applications/create-next-app/package.json
  packages/e2e-tests/test-applications/create-react-app/package.json
  packages/e2e-tests/test-applications/create-remix-app/package.json
  packages/e2e-tests/test-applications/nextjs-app-dir/package.json
  packages/e2e-tests/test-applications/nextjs-app-dir/test-recipe.json
  packages/e2e-tests/test-applications/node-express-app/package.json
  packages/e2e-tests/test-applications/react-create-hash-router/package.json
  packages/e2e-tests/test-applications/react-create-hash-router/test-recipe.json
  packages/e2e-tests/test-applications/standard-frontend-react-tracing-import/package.json
  packages/e2e-tests/test-applications/standard-frontend-react/package.json
  packages/e2e-tests/test-applications/standard-frontend-react/test-recipe.json
  packages/e2e-tests/test-applications/sveltekit/package.json
Labels: Type: Tests, Dev: Build

#8604 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#8603 test: Only run specified integration tests with firefox
  packages/browser-integration-tests/README.md
  packages/browser-integration-tests/package.json
  packages/browser-integration-tests/playwright.config.ts
  packages/browser-integration-tests/scripts/detectFlakyTests.ts
  packages/browser-integration-tests/suites/public-api/captureException/errorEvent/test.ts
  packages/browser-integration-tests/suites/replay/bufferMode/test.ts
  packages/browser-integration-tests/suites/replay/customEvents/test.ts
  packages/browser-integration-tests/suites/replay/errors/errorMode/test.ts
  packages/browser-integration-tests/suites/replay/errors/errorsInSession/test.ts
  packages/browser-integration-tests/suites/replay/largeMutations/defaultOptions/test.ts
  packages/browser-integration-tests/suites/replay/largeMutations/mutationLimit/test.ts
  packages/browser-integration-tests/suites/replay/privacyInput/test.ts
  packages/browser-integration-tests/suites/replay/privacyInputMaskAll/test.ts
  packages/browser-integration-tests/suites/replay/requests/test.ts
  packages/browser-integration-tests/suites/replay/sessionExpiry/test.ts
  packages/browser-integration-tests/suites/replay/sessionExpiry/test.ts-snapshots/snapshot-0-firefox.json
  packages/browser-integration-tests/suites/replay/sessionExpiry/test.ts-snapshots/snapshot-0.json
  packages/browser-integration-tests/suites/replay/sessionExpiry/test.ts-snapshots/snapshot-2-firefox.json
  packages/browser-integration-tests/suites/replay/sessionExpiry/test.ts-snapshots/snapshot-2.json
  packages/browser-integration-tests/suites/replay/sessionInactive/test.ts-snapshots/snapshot-0-firefox.json
  packages/browser-integration-tests/suites/replay/sessionInactive/test.ts-snapshots/snapshot-0.json
  packages/browser-integration-tests/suites/replay/sessionInactive/test.ts-snapshots/snapshot-1-firefox.json
  packages/browser-integration-tests/suites/replay/sessionInactive/test.ts-snapshots/snapshot-1.json
  packages/browser-integration-tests/suites/replay/sessionMaxAge/test.ts-snapshots/snapshot-0-firefox.json
  packages/browser-integration-tests/suites/replay/sessionMaxAge/test.ts-snapshots/snapshot-0.json
  packages/browser-integration-tests/suites/replay/sessionMaxAge/test.ts-snapshots/snapshot-2-firefox.json
  packages/browser-integration-tests/suites/replay/sessionMaxAge/test.ts-snapshots/snapshot-2.json
  packages/browser-integration-tests/suites/replay/slowClick/init.js
  packages/browser-integration-tests/suites/replay/slowClick/multiClick/test.ts
  packages/browser-integration-tests/suites/replay/slowClick/mutation/test.ts
  packages/browser-integration-tests/suites/replay/slowClick/template.html
  packages/browser-integration-tests/suites/replay/slowClick/timeout/test.ts
  packages/browser-integration-tests/suites/stacktraces/protocol_containing_fn_identifiers/test.ts
  packages/browser-integration-tests/suites/stacktraces/protocol_fn_identifiers/test.ts
  packages/browser-integration-tests/suites/stacktraces/regular_fn_identifiers/test.ts
  packages/browser-integration-tests/suites/tracing/browsertracing/backgroundtab-pageload/test.ts
  packages/browser-integration-tests/suites/tracing/browsertracing/http-timings/test.ts
  packages/browser-integration-tests/suites/tracing/browsertracing/interactions/test.ts
Labels: Type: Tests

#8623 meta(ci): Auto-add package label to new issues
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/workflows/issue-package-label.yml
Labels: Dev: CI

#8617 fix(replay): Use `session.started` for min/max duration check
  packages/browser-integration-tests/suites/replay/maxReplayDuration/init.js
  packages/browser-integration-tests/suites/replay/maxReplayDuration/template.html
  packages/browser-integration-tests/suites/replay/maxReplayDuration/test.ts
  packages/replay/src/replay.ts
  packages/replay/src/util/handleRecordingEmit.ts
Labels: Package: replay

#8630 meta(ci): Fix label mapper
  .github/workflows/issue-package-label.yml
Labels: Dev: CI

#8631 build: Update size limit config
  .size-limit.js
Labels: Dev: CI

#8648 fix(replay): Ignore clicks with `shift` pressed
  packages/replay/src/coreHandlers/handleDom.ts
Labels: Type: Bug, Package: replay

#8652 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow

#8683 [Gitflow] Merge master into develop
  CHANGELOG.md
  lerna.json
  packages/angular-ivy/package.json
  packages/angular/package.json
  packages/browser-integration-tests/package.json
  packages/browser/package.json
  packages/core/package.json
  packages/core/src/version.ts
  packages/e2e-tests/package.json
  packages/ember/package.json
  packages/eslint-config-sdk/package.json
  packages/eslint-plugin-sdk/package.json
  packages/gatsby/package.json
  packages/hub/package.json
  packages/integration-shims/package.json
  packages/integrations/package.json
  packages/nextjs/package.json
  packages/node-experimental/package.json
  packages/node-integration-tests/package.json
  packages/node/package.json
  packages/opentelemetry-node/package.json
  packages/overhead-metrics/package.json
  packages/react/package.json
  packages/remix/package.json
  packages/replay-worker/package.json
  packages/replay/package.json
  packages/serverless/package.json
  packages/svelte/package.json
  packages/sveltekit/package.json
  packages/tracing-internal/package.json
  packages/tracing/package.json
  packages/types/package.json
  packages/typescript/package.json
  packages/utils/package.json
  packages/vue/package.json
  packages/wasm/package.json
Labels: Dev: Gitflow
